DATA SEGMENT
    NUM1 DW 0258H,0258H      ;32 BIT SUBTRACTION IS DONE BY TAKING TWO 16 BIT 
    NUM2 DW 0019H,0019H
    DIFF DW 3 DUP<0>
    DATA ENDS
CODE SEGMENT
    ASSUME CS:CODE,DS:DATA
    START:MOV AX,DATA
    MOV DS,AX
    MOV BX,00H   ;INITIALIZE BX WITH 0000H
    MOV AX,NUM1  ;LOAD AX WITH NUM1
    SUB AX,NUM2  ;SUBTRACT NUM2 FROM AX
    MOV DIFF,AX  ;MOVE RESULT TO DIFF
    MOV AX,NUM1+2 ;LOAD SECOND PART OF NUM1 TO AX
    SBB AX,NUM2+2 ;SUBTRACT SECOND PART OF NUM2 FROM AX
    MOV DIFF+2,AX ;MOVE RESULT TO DIFF+2
    SBB BX,00H    ;SUBTRACT 0H FROM BX WITH BORROW
    MOV DIFF+4,DX ;MOVE RESULT TO DIFF+4
    MOV AH,4CH
    INT 21H
    CODE ENDS
END START
